version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user_12345
      POSTGRES_DB: hackathon
    ports:
      - 5432:5432
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://user:user_12345@db:5432/hackathon
    depends_on:
      - db

# volumes:
#   postgres-data:
#     driver: local